version: "3"
services:
    www:
        build: .
        ports: 
            - ${HTTP_PORT}
        volumes:
            - ./webroot:/var/www/html/
        links:
            - db
        networks: 
            - default
    
    db:
        image: mysql:latest
        ports:
            - "3306:3306"
        env_file:
            - ./.env
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
            - ./data:/var/lib/mysql
        networks: 
            - default
